version: '3'

services:
  app:
    build:
      context: ./
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - app.env
    restart: always
    networks:
      default:

  postgres:
    image: postgres:16.2
    restart: always
    env_file:
      - app.env
    networks:
      default:
